### ISSUE TITLE
SideEffects

### ISSUE THREAD

**Issue by rlacerda83** [PommeVerte/gremlin-php#10]
I think that's not a problem, is a doubt.
I'm having trouble using sideEffect to update properties of a vertex.

I am running the following code:
```php
$result = $connection->send("g.V(12360).sideEffect{it.name='Rodrigo'; it.idUser='10'}");
```

The error message:
```
A general server error occurred that prevented the request from being processed. : No such property: name for class: org.apache.tinkerpop.gremlin.process.traversal.traverser.O_Traverser >
```
This is the vertex contents:
```json
{
  "data": [
    {
      "id": 12360,
      "label": "user",
      "type": "vertex",
      "properties": {
        "idUser": [
          {
            "id": "3yh-9jc-2dh",
            "value": "2"
          }
        ],
        "name": [
          {
            "id": "3k9-9jc-sl",
            "value": "Lacerda"
          }
        ]
      }
    }
  ]
}```

**Comment by PommeVerte** [comment]
Hey @rlacerda83 ,

Your gremlin doesn't look correct. `it` inside `sideEffect` refers to a traverser object now (TP3). What you need to do is get the traversal object back from that and then change the properties:
```groovy
g.V(12360).sideEffect{it.get().property("name", "Rodrigo"); it.get().property("idUser", "10")}
```

Note that you can also do this directly with the following:

```groovy
g.V(12360).property("name", "Rodrigo").property("idUser", "10")
```
This is actually better as gremlin can use traversal strategies to optimize your query.

I'm closing this but feel free to ask more questions if you're having issues.

Best,
Dylan

**Comment by PommeVerte** [comment]
I forgot to mention this but the following also works if you need to use `sideEffect` for whatever reason:
```groovy
g.V(12360).sideEffect(property("name", "Rodrigo").property("idUser", "10"))
```

**Comment by rlacerda83** [comment]
You're right, I'm confusing the returned types, need to read more carefully the documentation.

Thank you very much for your help.

I am creating a microservice for product recommendations in PHP, and I'm using your library.

I will start with this implementation, cosine similarity!
https://gist.github.com/dkuppitz/79e0b009f0c9ae87db5a

Maybe I need your help with something else ... = )

**Comment by PommeVerte** [comment]
No problem. :)

Your project sounds interesting. Do let me know if you need any extra help. You can also find plenty of help in the [gremlin-users](https://groups.google.com/forum/#!forum/gremlin-users) mailing list if I'm not around.

Best of luck.

**Comment by rlacerda83** [comment]
It can run script blocks in your library?
For example:
```
def v = g.V. () has ("key", "value")
ElementHelper.setProperties (v.hasNext () v.next (?): G.addVertex () properties)
```
I am creating some predefined functions, but not sure how to use with your library.

thks!

**Comment by PommeVerte** [comment]
Technically yes. Any gremlin code block is valid to send (e.g scripts on multiple lines with variables and semicolons).
You should even be able to use tha Java API

**Comment by PommeVerte** [comment]
If you want to create a predefined step though it is probably best to do it in the servers configured startup script (/scripts folder)

**Comment by PommeVerte** [comment]
If something is unclear let me know. I've already built some level of abstraction over the driver so chances are I've faced the same problem at one point.

**Comment by rlacerda83** [comment]
I did as you suggested, write multiple lines separated by semicolons:

```php
  $query = "v = g.V().has('id','55');
      v.hasNext() ? v.next().property('id', '55 next') : g.addV('name','id55 Agora sim','id','55');";
```

It worked!

I do not want to put the scripts on the server for ease of installation, maintenance and use.
Thank you again!

**Comment by PommeVerte** [comment]
Great!

If this is a piece of code that is going to be reused with changing parameters I suggest you use `Message::bindValue()` instead of putting the values directly in the script. It would look something like : 

```php
$db = new Connection([
   'host' => 'localhost',
   'graph' => 'graph'
]);
$query = "v = g.V().has('id',BIND_ID);
      v.hasNext() ? v.next().property('id', BIND_NEW_ID) : g.addV('name',BIND_NAME,'id',BIND_ID);";
$db->message->bindValue("BIND_ID", "55");
$db->message->bindValue("BIND_NEW_ID", "55 next");
$db->message->bindValue("BIND_NAME", "id55 Agora sim");
$db->send($query);
```

Maybe I can add support for `bindValues()` to make things simpler.

The reason why you would want to do this is that gremlin-server will compile your script at runtime and then cache it. If you use the binds like above then the server will only need to compile this script once. Every other call will fetch the compiled script from cache.

If you leave it like you did in you post, then every time one of those values changes the server will need to compile the script again and it will cost you quite some time.

**Comment by rlacerda83** [comment]
Hello again!

I implemented the binds , thank you for your help.

Now I have a little problem to generate mass! When i run this script, only the second row is inserted.
```php
$db = new Connection([
   'host' => 'localhost',
   'graph' => 'graph'
]);

$db->send("person1 = g.addV(label, 'person', 'name', 'Michael Sherman');
                   person2 = g.addV(label, 'person', 'name', 'Zoltan Varju');");
```
Any idea?

Thks!

**Comment by PommeVerte** [comment]
Yes this is one of the tricky aspects of gremlin. Anything with `g` needs to be iterated in one way or another. `gremlin-server` has the nice (or nasty depending on your point of view) habit of iterating the last line automatically so it's not always apparent to people what's going on.

In short the following should work:
```php
$db = new Connection([
   'host' => 'localhost',
   'graph' => 'graph'
]);

$db->send("person1 = g.addV(label, 'person', 'name', 'Michael Sherman').iterate();
                   person2 = g.addV(label, 'person', 'name', 'Zoltan Varju').iterate();"); // this last iterate is not necessary as gremlin-server does it automatically.
```

Instead you could also use `graph.addVertex()` where there's no need to iterate : 
```php
$db = new Connection([
   'host' => 'localhost',
   'graph' => 'graph'
]);

$db->send("person1 = graph.addVertex(label, 'person', 'name', 'Michael Sherman');
                   person2 = graph.addVertex(label, 'person', 'name', 'Zoltan Varju');");
```

If you need more info on iterating (because I know it's hard to grasp) let me know.

**Comment by PommeVerte** [comment]
I've amended my answer earlier by replacing `iterate()`with `next()` since iterate will return NULL and you want to store the value in `personX`.
