### ISSUE TITLE
What's the right configuration for Gremlin server?

### ISSUE THREAD

**Issue by mohataher** [PommeVerte/gremlin-php#16]
What is the right .yaml configuration that I should use for the Gremlin server in order to connect the client?

I get an error 
```text
:> g.traversal().V(100).next()
WARN  org.apache.tinkerpop.gremlin.driver.MessageSerializer  - Response [PooledUnsafeDirectByteBuf(ridx: 30, widx: 30, cap: 30)] could not be deserialized by org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0.
```

**Comment by PommeVerte** [comment]
It's the version that's in the `build` folder : https://github.com/PommeVerte/gremlin-php/blob/master/build/server/gremlin-server-php.yaml

The relevant lines are for your error are:
```
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV1d0 }                                 
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0 }
```

**Comment by PommeVerte** [comment]
I wanted to elaborate a bit more on this but normally the default `gremlin-server.yaml` should be properly configured and work out of the box (for Tinkerpop 3.0.2)

as per : https://github.com/apache/incubator-tinkerpop/blob/tp30/gremlin-server/conf/gremlin-server.yaml

**Comment by mohataher** [comment]
I had a look at your configuration `.yaml` file and noticed I don't have the `gremlin-php-script.groovy` in `scripts` directory of the server. I will add that script and check again. I will keep you posted.

**Comment by PommeVerte** [comment]
normally the default `gremlin-server.yaml` + `empty-sample.groovy script` should work as well provided you have a an up to date version of the server. (TP 3.0.2 preferably as there are some important corrections)
The yaml and groovy files I linked to (in the `build` folder) do more than what you probably need, and will fail if you don't install the Neo4j dependencies like described in the testing section of the `README`.

Instead you should preferably use the following files : 
[gremlin-server.yaml](https://github.com/apache/incubator-tinkerpop/blob/tp30/gremlin-server/conf/gremlin-server.yaml)
[empty-sample.groovy](https://github.com/apache/incubator-tinkerpop/blob/tp30/gremlin-server/scripts/empty-sample.groovy)

**Comment by PommeVerte** [comment]
This seems mostly like a configuration issue so I'm going to close this. Feel free to continue asking here if you're still having issues. I'm more than happy to help out more.

**Comment by mohataher** [comment]
Hello, thank you so much for your help. Yes, it was a configuration issue and had nothing to do with `gremlin-php`.

The right configuration is presented here in this [answer](http://stackoverflow.com/questions/33677046/gremlin-console-json-response-doesnt-work/33678097#33678097) for Titan DB that should be queried by `gremlin-php`.
