### ISSUE TITLE
Driver connects to the server, but cannot find any data

### ISSUE THREAD

**Issue by grreeenn** [PommeVerte/gremlin-php#32]
Hello,

I'm quite new to Titan, but I really like it and currently trying to build the PHP app on it - so thank you for your driver :)

At the moment I run Titan 1.0 on Cassandra (all of the settings and configs - out of the box). I've populated the graph with data I needed and I succeed to get it through Gremlin console; but when I run even the simplest sample, like
```
require_once('vendor/autoload.php');
use \Brightzone\GremlinDriver\Connection;



$db = new Connection([
    'host' => 'localhost',
    'port' => 8182,
    'graph'=> 'graph'
]);

$db->open();
$query = "g.V()";
$result = $db->send($query);
var_dump($result);
```
I get a message that says "The server processed the request but there is no result to return (e.g. an {@link Iterator} with no elements)". Calculations queries (like $db->send("5+5")) works though, so I know that the connection is somehow correct; I suspect the graph name to be the issue - but don't know how to get the right one. I've tried to add 'standardtitangraph' (this is the instance name that's returned on graph creation in Gremlin console), 'tinkergraph', and even a full constructor that I pass to gremlin console to open a graph ('TitanFactory.open('../conf/titan-cassandra-es.properties')') - but none of them worked. I feel that I miss something really basic, but still - could you please help me with this one?

Thanks,
Gregory

**Comment by PommeVerte** [comment]
Hey Gregory.

The error you are getting is actually the driver directly verbosing the server error. You will get this everytime you get an empty result set. You can either catch this yourself to log a warning that may help when debugging or you can use the `emptySet` driver option:
```php
$db = new Connection([
    'host' => 'localhost',
    'port' => 8182,
    'graph' => 'graph',
    'emptySet' => TRUE
]);
``` 
This is just a detail and not the issue at hand.

To find your graph name it should be defined in the `conf/gremlin-server/gremlin-server.yaml` file. If you're running a standard version then it should be `graph`. 

There are plenty of possible issue here. Could you tell me how you populate the graph in the first place? (what scripts you ran and where)

**Comment by grreeenn** [comment]
Hello Dylan,

Thank you for your swift response - it helped me to solve the problem :)
The problem was, that in out-of-the-box configuration (at least, when downloading Titan from the official website and not forking from GitHub) Gremlin Server is configured to work only with BerkleyDB. The problem is described [here](https://github.com/thinkaurelius/titan/issues/1259) - so I took this hing, went to [Titan GitHub repo](https://github.com/thinkaurelius/titan/tree/titan11/titan-dist/src/assembly/static/conf/gremlin-server), and downloaded the cassandra-related configs - now it works great! 

Thank you again! :)

**Comment by PommeVerte** [comment]
Glad you sorted it out!! :)
