### ISSUE TITLE
Gremlin server out of memory

### ISSUE THREAD

**Issue by rlacerda83** [PommeVerte/gremlin-php#33]
Hello!! 

Is there a way to pass the parameter of this post?

(https://stackoverflow.com/questions/33264198/titandb-gremlin-server-running-out-of-memory-how-to-set-jsr223-groovy-engine-ke/33279384)

I am having this problem in some scripts.

**Comment by PommeVerte** [comment]
That is a good question. I'll have to look into it. Can you not rather set you gremlin server configuration up differently for this?

**Comment by PommeVerte** [comment]
wow ok this is super late which is ridiculous given how that answer should be straightforward to implement with the driver (it's in the README.md). Really sorry about that.

The following should be the equivalent of what the response there was : 
```php
$db = new Connection([
    'host' => 'localhost',
    'port' => 8182,
    'graph' => 'graph',
]);
$db->open();

$db->message->bindValue("#jsr223.groovy.engine.keep.globals", "phantom"); 
$result = $db->send('g.V()'); // The server will treat this in cache with the phantom option
//do something with result
$db->close();
```
