### ISSUE TITLE
PHP7 Warnings on $db->send(...)

### ISSUE THREAD

**Issue by shean42** [PommeVerte/gremlin-php#34]
Hi all,

Using PHP 7.1.5 I'm experiencing warnings in the error_log as follows:

PHP Warning:  Parameter 1 to Brightzone\\GremlinDriver\\Connection::Brightzone\\GremlinDriver\\{closure}() expected to be a reference, value given in [...]/vendor/brightzone/gremlin-php/src/Workload.php on line 78

These warnings seem to appear for every $db->send command, and thus there are quite a lot of them piling up in the log. Maybe someone has an idea on how to get rid of these (without changing the log level :-)

**Comment by PommeVerte** [comment]
Thanks @shean42 I'll have a look at this this weekend :)

**Comment by The-Don-Himself** [comment]
Any word on this @PommeVerte ? It actually prevents code from running in environments like dev where warnings abort execution.

**Comment by PommeVerte** [comment]
Hey this should be fixed on master. Sorry it took so long I've been trying to tackle a few things here before the next release. 

If you need a clean composer release please expect it either later today or tomorrow.
I'll be closing this but let me know if you're still experiencing this. 

Cheers.
