### ISSUE TITLE
Cant receive data

### ISSUE THREAD

**Issue by rlacerda83** [PommeVerte/gremlin-php#4]
Hello,

I can not run the sample code, the following error appears :
Notice: Undefined offset: 1 in /var/www/html/gremlin/vendor/brightzone/gremlin-php/src/Connection.php on line 211

Warning: unpack(): Type C: not enough input, need 1, have 0 in /var/www/html/gremlin/vendor/brightzone/gremlin-php/src/Connection.php on line 214

Warning: array_values() expects parameter 1 to be array, boolean given in /var/www/html/gremlin/vendor/brightzone/gremlin-php/src/Connection.php on line 214

Fatal error: Uncaught exception 'brightzone\rexpro\ServerException' with message 'A general server error occurred that prevented the request from being processed. : Empty reply. Most likely the result of an irregular request. (Check custom Meta, or lack of in the case of a non-isolated query)' in /var/www/html/gremlin/vendor/brightzone/gremlin-php/src/Connection.php:620 Stack trace: #0 /var/www/html/gremlin/vendor/brightzone/gremlin-php/src/Connection.php(268): brightzone\rexpro\Connection->error('Empty reply. Mo...', 500) #1 /var/www/html/gremlin/vendor/brightzone/gremlin-php/src/Connection.php(358): brightzone\rexpro\Connection->socketGetUnpack() #2 /var/www/html/gremlin/index.php(11): brightzone\rexpro\Connection->send() #3 {main} thrown in /var/www/html/gremlin/vendor/brightzone/gremlin-php/src/Connection.php on line 620

My code:
require_once('vendor/autoload.php');
use \brightzone\rexpro\Connection;

$db = new Connection;
$db->open('localhost', 'graph');
$db->message->gremlin = '100-1';
$db->send();
$db->close();

I'm with the 0.9.0 -M2 version with Titan 0.9.0 and 3.0.0 Gremlin .

**Comment by PommeVerte** [comment]
Looking at this right now

**Comment by rlacerda83** [comment]
Ah!
When the script runs , the CPU processing rises and takes about 1 minute to generate the error.

I am suspicious of anything of my environment , but the Rest API works, and the connection by Gremlin in the terminal too!

**Comment by PommeVerte** [comment]
ok So... I can't seem to recreate this (at least not in a simple fashion). 
I am using a vanilla `titan-0.9.0-M2-hadoop1` downloaded from http://s3.thinkaurelius.com/downloads/titan/titan-0.9.0-M2-hadoop1.zip on ubuntu 14.04 LTS and I'm getting the expected result of `[99]`

Could you perhaps share your environment details? (os, java version, etc.) And possibly the Titan configuration files you are using if they're different from the default?

My project has a test.php file with the above code and a composer.json file with : 
```json
{
    "name": "root/testing",
    "require": {
        "brightzone/gremlin-php": "*"
    },
    "authors": [
        {
            "name": "Dylan Millikin",
            "email": "dylan.millikin@brightzone.fr"
        }
    ],
    "minimum-stability": "stable"
}
```

Also worth exploring: Could you run titan via `bin/titan.sh -v start` and see if any errors are thrown (either on gremlin-server startup or when gremlin-php queries the server)?

Thanks

**Comment by rlacerda83** [comment]
I run ubuntu 15.
Java version:
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
openjdk version "1.8.0_45-internal"
OpenJDK Runtime Environment (build 1.8.0_45-internal-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)

My gremlin-server.yaml

```
host: localhost
port: 8182
threadPoolWorker: 1
gremlinPool: 8
scriptEvaluationTimeout: 30000
serializedResponseTimeout: 30000
channelizer: org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer
#channelizer: org.apache.tinkerpop.gremlin.server.channel.HttpChannelizer
graphs: {
  #graph: conf/gremlin-server/titan-berkeleyje-server.properties
  graph: conf/titan-cassandra-es.properties
}
plugins:
  - aurelius.titan
  - tinkerpop.tinkergraph
scriptEngines: {
  gremlin-groovy: {
    imports: [java.lang.Math],
    staticImports: [java.lang.Math.PI],
    scripts: [scripts/empty-sample.groovy]},
  nashorn: {
      imports: [java.lang.Math],
      staticImports: [java.lang.Math.PI]}}
serializers:
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0, config: { useMapperFromGraph: graph }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0, config: { serializeResultToString: true }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV1d0, config: { useMapperFromGraph: graph }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0, config: { useMapperFromGraph: graph }}
processors:
  - { className: org.apache.tinkerpop.gremlin.server.op.session.SessionOpProcessor, config: { sessionTimeout: 28800000 }}
metrics: {
  consoleReporter: {enabled: true, interval: 180000},
  csvReporter: {enabled: true, interval: 180000, fileName: /tmp/gremlin-server-metrics.csv},
  jmxReporter: {enabled: true},
  slf4jReporter: {enabled: true, interval: 180000},
  gangliaReporter: {enabled: false, interval: 180000, addressingMode: MULTICAST},
  graphiteReporter: {enabled: false, interval: 180000}}
threadPoolBoss: 1
maxInitialLineLength: 4096
maxHeaderSize: 8192
maxChunkSize: 8192
maxContentLength: 65536
maxAccumulationBufferComponents: 1024
resultIterationBatchSize: 64
writeBufferHighWaterMark: 32768
writeBufferHighWaterMark: 65536
ssl: {
  enabled: false}
```
In console show this error when i run the php script

338657 [gremlin-server-worker-1] WARN  org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler  - Invalid request - responding with 400 Bad Request and no gremlin script supplied

**Comment by PommeVerte** [comment]
Great thanks for the info. And just to make sure, the version of gremlin-php you're using is `v1.0`? 
I'll recreate the above env and test.

**Comment by rlacerda83** [comment]
Yes! v1.0
```
"name": "brightzone/gremlin-php",
        "version": "v1.0",
        "version_normalized": "1.0.0.0",
        "source": {
            "type": "git",
            "url": "https://github.com/PommeVerte/gremlin-php.git",
            "reference": "dcde94ca290fc16f8f806fa463a339051215c49a"
        },
```

**Comment by PommeVerte** [comment]
ok, odd. and what version of PHP? (forgot to ask)

**Comment by rlacerda83** [comment]
```
PHP 5.6.4-4ubuntu6.2 (cli) (built: Jul  2 2015 15:29:28) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
```

**Comment by rlacerda83** [comment]
Hey!

Its works!

I shutdown the titan , updated ubuntu and updated java .

Started the titan and works!

A strange behavior that I saw was that time was about 5 processes Gremlin server running , I do not know if this is normal , and may have been the problem , why now only have one .

Thanks, and sorry for wasting your time.

**Comment by PommeVerte** [comment]
Hey no problem.

I think I know what you mean. If you forget to stop titan and start it again it will start another instance and everything goes crazy (I can't even seem to be able to stop titan without killing the processes manually).

I just wanted to give you a heads up about 
```
338657 [gremlin-server-worker-1] WARN org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler - Invalid request - responding with 400 Bad Request and no gremlin script supplied
```
As it is an odd error to get at all (400 isn't a valid error code as per the documentation) This might indicate an incorrect configuration. It might come from using `HttpChannelizer` instead of `WebSocketChannelizer`, though I'm not sure about this.

Anyways, glad it worked out. Let me know if you need any help with anything.
