### ISSUE TITLE
Connection Error in Connection.php

### ISSUE THREAD

**Issue by ge33ek** [PommeVerte/gremlin-php#41]
Hi Team,

Azure Web App, Azure CosmosDB (Gremlin), Tried on 5.6, 7.0, 7.1

Any suggestions, error isn't particularly helpful.

Config as:

```
$db = new Connection([
  'host' => 'MYDB.graphs.azure.com',
  'port' => 443,
  'graph' => 'graph',
  'username' => '/dbs/MYDB/colls/MYCOL',
  'password' => 'ReallyImportantStuff',
  'ssl' => [
    "ssl"=> [
        "cafile" => "%ProgramFiles(x86)%\Git\bin\curl-ca-bundle.crt",
        "verify_peer"=> true,
        "verify_peer_name"=> true,
    ]
]
]);
```

Returns:

```
Fatal error: Uncaught exception 'Brightzone\GremlinDriver\InternalException' with message 'gremlin-php driver has thrown the following error : ' in D:\home\site\wwwroot\vendor\brightzone\gremlin-php\src\Connection.php:791
Stack trace:
#0 D:\home\site\wwwroot\vendor\brightzone\gremlin-php\src\Connection.php(373): Brightzone\GremlinDriver\Connection->error('', 0, true)
#1 D:\home\site\wwwroot\vendor\brightzone\gremlin-php\src\Connection.php(153): Brightzone\GremlinDriver\Connection->connectSocket()
#2 D:\home\site\wwwroot\index.php(26): Brightzone\GremlinDriver\Connection->open()
#3 {main}
  thrown in D:\home\site\wwwroot\vendor\brightzone\gremlin-php\src\Connection.php on line 791
```

**Comment by PommeVerte** [comment]
Hey!

Can you share your `gremlin-php` version as well as the `gremlin-server.yaml` file please?

**Comment by ge33ek** [comment]
Hey @PommeVerte - Thanks for the super quick response!!

Just pulled it down, so latest version.

gremlin-server-php.yaml - attached (-secure is the same, in case that makes a dif)
```

host: MYDB.graphs.azure.com
port: 443
threadPoolWorker: 1
gremlinPool: 8
scriptEvaluationTimeout: 30000
serializedResponseTimeout: 30000
channelizer: org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer
graphs: {
  graph: conf/tinkergraph-empty.properties ,
  graphT: conf/neo4j-empty.properties
}
plugins:
  - tinkerpop.neo4j
  - tinkerpop.tinkergraph
scriptEngines: {
  gremlin-groovy: {
    imports: [java.lang.Math],
    staticImports: [java.lang.Math.PI],
    scripts: [scripts/gremlin-php-script.groovy]},
  nashorn: {
      imports: [java.lang.Math],
      staticImports: [java.lang.Math.PI]}}
serializers:
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0, config: { useMapperFromGraph: graph }}            # application/vnd.gremlin-v1.0+gryo
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0, config: { serializeResultToString: true }}        # application/vnd.gremlin-v1.0+gryo-stringd
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV1d0, config: { useMapperFromGraph: graph }} # application/vnd.gremlin-v1.0+json
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0, config: { useMapperFromGraph: graph }}        # application/json
processors:
  - { className: org.apache.tinkerpop.gremlin.server.op.session.SessionOpProcessor, config: { sessionTimeout: 28800000 }}
metrics: {
  consoleReporter: {enabled: true, interval: 180000},
  csvReporter: {enabled: true, interval: 180000, fileName: /tmp/gremlin-server-metrics.csv},
  jmxReporter: {enabled: true},
  slf4jReporter: {enabled: true, interval: 180000},
  gangliaReporter: {enabled: false, interval: 180000, addressingMode: MULTICAST},
  graphiteReporter: {enabled: false, interval: 180000}}
strictTransactionManagement: false
threadPoolBoss: 1
maxInitialLineLength: 4096
maxHeaderSize: 8192
maxChunkSize: 8192
maxContentLength: 65536
maxAccumulationBufferComponents: 1024
resultIterationBatchSize: 64
writeBufferHighWaterMark: 32768
writeBufferHighWaterMark: 65536
ssl: {
  enabled: false}
```

**Comment by PommeVerte** [comment]
Ok, I'm not entirely sure on how the azure cosmoDB scene functions but if you have access to the gremlin server yaml I'm going to assume that it will be referencing cosmoDB somewhere in this section : 

```yaml
graphs: {
  graph: conf/tinkergraph-empty.properties ,
  graphT: conf/neo4j-empty.properties
}
plugins:
  - tinkerpop.neo4j
  - tinkerpop.tinkergraph
```
(which, btw, you will want to remove reference to neo4j as this might make gremlin server fail on start unless you manually install the neo4j dependencies).

If your ssl section is the same then perhaps try without the certificate first? :
```php
 $db = new Connection([
            //...
            'ssl' => [
                "ssl"=>[
                    "verify_peer"=>false,
                    "verify_peer_name"=>false,
                ]
            ],
        ]);
```
Hopefully that works and we can figure out how to get your certificate working. 

As a side note it might be useful to share the gremlin server startup logs.

**Comment by ge33ek** [comment]
Thanks @PommeVerte 
Disabling SSL requirements has indeed resolved the connectivity issue. Seems to be certificate related then. I'll see to injecting some error checking and reporting of that.

I've removed the reference to neo4.

As to startup logs, where does traditionally find these? Happy to send them through.

**Comment by PommeVerte** [comment]
Ok that's good.
The logs are traditionally in `/gremlin-server/logs/`. 
Also I just noticed that your `gremlin-server.yaml` has ssl disabled so you can remove the `ssl` section entirely from the `Connection()` config.

With that said you should still be able to enable ssl easily without certificates. This will at least enable secure communication and a level of authentication.

The details for the `gremlin-server.yaml` configuration file can be found here : https://github.com/PommeVerte/gremlin-php/blob/master/build/server/3.2.x/gremlin-server-php-secure.yaml#L70-L75
And an example that works with the above can be found here : https://github.com/PommeVerte/gremlin-php/blob/master/tests/AuthTest.php#L16-L36

**Comment by PommeVerte** [comment]
Azure CosmoDB seems to handle some configuration through the interface. I'm not entirely sure what things are like in the background, or if you have access to the actual configuration files. But with a bit of tinkering I'm sure we can figure something out.
