### ISSUE TITLE
valueMap(true) fails to serialize

### ISSUE THREAD

**Issue by crearc** [PommeVerte/gremlin-php#51]
The command works fine in the gremlin console, but fails to serialize when returned.

Command: `g.V().limit(1).valueMap(true)`

Expected Return: {label=User, id=someid123, count=1}

Actual Error Returned:
```
gremlin-php driver has thrown the following error : 
Item type 'g:T' is not currently supported by the serializer
(Brightzone\GremlinDriver\Serializers\Gson3)
```

The value of `$item` passed into `deconvert` that it fails on is:
```
array(2) {
  ["@type"]=>
  string(3) "g:T"
  ["@value"]=>
  string(5) "label"
}
```
`g:T` is also the type for `id`.

 `g.V()limit(1).valueMap()` works fine through gremlin-php and console, just not with the `true` (which is supposed to include the id and label instead of just properties).

**Comment by PommeVerte** [comment]
Hey @crearc  Thanks for the feedback. Can you tell me what version of TinkerPop you are using? Thanks.

**Comment by crearc** [comment]
@PommeVerte should have clarified! I'm running off of AWS Neptune which is Tinkerpop3 and Gremlin 3.4.0

**Comment by crearc** [comment]
Thanks @PommeVerte! Appreciate you building this and maintaining and being responsive. :)

Workaround 1) I've already attempted, but Neptune currently doesn't make available `WithOptions` (which I'm going to message them about as well).

I'll try number 2 though!

**Comment by crearc** [comment]
Just a note that number 2 doesn't work for Neptune (a lot still isn't implemented for it) and I can't change the gremlin configuration on the server. 

Any luck on the changes?

**Comment by crearc** [comment]
Just made a PR. Seems to work for me!

https://github.com/PommeVerte/gremlin-php/pull/52

**Comment by crearc** [comment]
Awesome @PommeVerte thank you!
