### ISSUE TITLE
Cannot use transactions when connecting to Azure CosmosDB

### ISSUE THREAD

**Issue by ephraimlambarte** [PommeVerte/gremlin-php#54]
Im connecting to Azure CosmosDB, and everthing works fine but when i add 'graph' key to connection array, i get gremlin query compilation error.

This is the error when i use 'graphT' just like in your examples:

 `Gremlin Query Compilation Error: Unable to resolve symbol 'graphT' in the current context. @ line 1, column 1.`

**Comment by PommeVerte** [comment]
cleaning up a bit. If you're still having issues feel free to let me know
