### ISSUE TITLE
I couldn't connect to OrientDB 

### ISSUE THREAD

**Issue by Metehan** [PommeVerte/gremlin-php#7]
Hi for orientDB connection i tried several connection string but non of them worked.

$db->open('localhost:2480/command/GratefulDeadConcerts/gremlin/', 'g','root','pass');

$db->open('localhost:2480/', 'g','root','pass');

$db->open('localhost:2480/command/', 'g','root','pass');

...

**Comment by PommeVerte** [comment]
Hi @Metehan,

gremlin-php is a driver for [gremlin server](http://tinkerpop.incubator.apache.org/docs/3.0.1-incubating/#gremlin-server) that was introduced in the [Tinkerpop 3 (TP3)](http://www.tinkerpop.com) stack. Orient is currently working on an implementation of TP3 but does not as of yet support it. 

However, there is an implementation for TP 2.x and you can run an orient graph inside the [Rexster](https://github.com/tinkerpop/rexster/wiki) server (old name of gremlin server). You can find how to configure rexster for orient [here](https://github.com/tinkerpop/rexster/wiki/Specific-Graph-Configurations#orientdb). And find a php driver for it [here](https://github.com/PommeVerte/rexpro-php).

---

If you would like to run the OrientDb server directly you will need to use an orient specific driver such as [PhpOrient](https://github.com/Ostico/PhpOrient).

Or if you would like to keep the advantages of querying in gremlin and changing DBs on the fly (in a DB agnostic environment) you can checkout [Spider](https://github.com/spider/spider) that is still a WIP project but already supports a DB agnostic driver. If you decide to go the Spider way please let me know here, or open an issue in the repo about using gremlin in OrientDB as we should be able to implement it pretty quickly and walk you through the process.

Best,
Dylan

**Comment by Metehan** [comment]
Hi Dylan,
Thanks for your interest and detailed answer :)

I am currently using PhpOrient but i was looking for a database agnostic driver. Your "Spider" is looking great, i am very much interested. As i see traversal queries are not implemented yet. I starred the repo i'll try it after v0.4.

Kind regards,
Metehan

**Comment by PommeVerte** [comment]
No problem, it's always nice seeing the php graph community working it's way around.

As a bit of extra information:
An OrientDB TP3 implementation should be released along side OrientDB 3.0 from what I understand. So at that time this driver should become relevant to you.

Cheers
